apiVersion: kubecluster.org/v1alpha1
kind: KubeCluster
metadata:
  labels:
    app.kubernetes.io/part-of: kubecluster
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubecluster
  name: pbspro-ubuntu-sample
spec:
  clusterType: pbspro
  clusterReplicaSpec:
    Server:
      replicas: 1
      template:
        spec:
          containers:
            - name: kubenode
              image: ubuntu
              # Comment out the below resources to use the CPU.
              resources:
                limits:
                  memory: 2Gi
                  cpu: 2
                requests:
                  memory: 2Gi
                  cpu: 2
    Cpu:
      replicas: 1
      template:
        spec:
          containers:
            - name: kubenode
              #              image: registry.cn-hangzhou.aliyuncs.com/eflops/slurm-dev:sysbench
              image: ubuntu
              resources:
                limits:
                  memory: 2Gi
                  cpu: 2
                requests:
                  memory: 2Gi
                  cpu: 2
