apiVersion: kubecluster.org/v1alpha1
kind: KubeCluster
metadata:
  labels:
    app.kubernetes.io/part-of: kubecluster
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubecluster
  name: slurm-centos-hostnetwork-sample
spec:
  clusterType: slurm
  clusterReplicaSpec:
    Controller:
      replicas: 1
      template:
        spec:
          hostNetwork: true
          containers:
            - name: kubenode
              image: centos
              command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 36000']
              # Comment out the below resources to use the CPU.
              resources:
                limits:
                  memory: 2Gi
                  cpu: 2
                requests:
                  memory: 2Gi
                  cpu: 2
    cpu:
      replicas: 1
      template:
        spec:
          hostNetwork: true
          containers:
            - name: kubenode
              image: centos
              resources:
                limits:
                  memory: 2Gi
                  cpu: 2
                requests:
                  memory: 2Gi
                  cpu: 2
